version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: gestion-vuelos-db
    environment:
      - POSTGRES_DB=db_sitas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gestion-vuelos-network

volumes:
  postgres-data:

networks:
  gestion-vuelos-network:
    driver: bridge
